# Generated by Django 4.0.6 on 2022-09-21 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nombre',
            new_name='materia',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='camada',
            new_name='numero',
        ),
    ]
